# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a711b90091e1b28fb41000973be4b4ddd1dbb70cb61d464ca78919f4dbfdf0e3e5c0e91f2cc61f205f209bc966998df0f188f4a727bb712657c9f27225c816b0

test:
  secret_key_base: 84a88ba89aba7678737d8524fc9b53cd019fa68a27722c063c5850f435837a5983fec8b70d67f516851639c6b4fb2cdf4c931c8ffaa17d5454d8b7f47499126b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
